---
- hosts: pis
  become: true
  tasks:
  - name: Add cgroup for Memory limits to bootparams
    lineinfile:
      dest: /boot/cmdline.txt
      regexp: '^(.*?)(\s*cgroup_enable=cpuset\s*)?$'
      line: '\1 cgroup_enable=cpuset'
      backrefs: true
      state: present
