---
- hosts: pi[5:8]
  remote_user: pi
  become: yes
  vars:
    pwlibsversion: "1.7"
    pwomxpversion: "20130815"
  tasks:  
    - name: download and install package pwlibs1    
      apt: deb=http://dl.piwall.co.uk/pwlibs1_{{ pwlibsversion }}_armhf.deb      
    - name: download and install package pwomxplayer
      apt: deb=http://dl.piwall.co.uk/pwomxplayer_{{ pwomxpversion }}_armhf.deb
    - name: create piwall-config
      template: src=templates/piwall.j2 dest=/home/pi/.piwall owner=pi group=pi mode=0644
    - name: create pitile-config
      template: src=templates/pitile.j2 dest=/home/pi/.pitile owner=pi group=pi mode=0644
    - name: configure rc.local for autostart piwall
      lineinfile: state=present path=/etc/rc.local line='pwomxplayer --config=4bez udp://239.0.1.23:1234?buffer_size=1200000B'
