---
- hosts: pi5,pi6,pi7,pi8
  become: true
  tasks:
  - name: install synergy-package
    apt: name=synergy state=present
  - name: setup display
    shell: export DISPLAY=:0
  - name: create synergy-config
    template: src=templates/synergy.j2 dest=/root/.synergy.conf owner=pi group=pi mode=0644
  - name: start server
    shell: synergys
    when: inventory_hostname == "pi8"
  - name: start clients
    shell: synergyc pi8
    when: inventory_hostname != "pi8"
#  - name: notification
#    shell: export DISPLAY=:0;export XAUTHORITY=~pi/.Xauthority;gxmessage "synergy is now up!" -timeout 5
    
#  - name: install supervisor-package
#    apt: name=supervisor state=present
#    when: synergy != "server"
#  - name: create supervisorconf
#    template: src=templates/synergyc.j2 dest=/etc/supervisor/conf.d/synergyc.conf
#    when: synergy != "server"
#  - name: reread supervisor
#    raw: supervisorctl reread
#    when: synergy != "server"
#  - name: update supervisor
#    raw: supervisorctl update
#    when: synergy != "server"
